#################################################### Test  AUTH ###################################################
### Test /api/v1/login
POST http://localhost:9090/api/v1/login
Content-Type: application/json
Cache-Control: no-cache

{
  "Token": "test-token"
}

### Test /token/refresh
POST http://localhost:9090/api/v1/token/refresh
Content-Type: application/json
Cache-Control: no-cache

{
  "jweToken": "{\"protected\":\"eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0\",\"aad\":\"eyJleHAiOiIyMDE4LTExLTIxVDIwOjMwOjIwKzA4OjAwIiwiaWF0IjoiMjAxOC0xMS0yMVQyMDoxNToyMCswODowMCJ9\",\"encrypted_key\":\"mjqI30nPCRsbmRg_rMQPxYw5YLRpN-bXePKJzt4Ga0yCPO2Kz3cTSXuwy5cxEdjNQaXbyZ7ztxXgVE83EeUvoN7XG9DLKsFiECH7ZsXTt_Xov2e5XoHXdUWv_pQZRJfWcSyQ2zv5uSA9LbjT2JFNYV9VxOLw6SMocU1YJxu1KwiRteGEQvZ0y9wuCDMY8UkJFrtDBCt0DaTBmLLX1jyT4PBPPbMCnujtPH7E0JNlMjmVCSOEDTQMdrC4jcVescqcGrS-T8YrKejUVRwANKOtOruzIhKYBLDIII2RgiV9redfdPRy847ydOsTHfOQ3J92OyZAYpNrZtGbMGNjsWniUw\",\"iv\":\"omP6G1AXuZ4eOcri\",\"ciphertext\":\"-HfZn6q58cFj2EEizyciOEZvCB2jLED4MvOi3FTBMllseAWt5-QYBDC-lO4\",\"tag\":\"Tg1yDcQ7GTU3sHMa4QDVzA\"}"
}

### Test /login/modes
GET http://localhost:9090/api/v1/login/modes
Accept: application/json
Cache-Control: no-cache

### Test /login/skippable
GET http://localhost:9090/api/v1/login/skippable
Accept: application/json
Cache-Control: no-cache


################################################### Test  csrfToken ################################################
### Test /api/v1/csrftoken/{action}
GET http://localhost:9090/api/v1/csrftoken/get
Content-Type: application/json
Cache-Control: no-cache

################################################### Test CRUD POD ###################################################
### Test /api/v1/pod
GET http://localhost:9090/api/v1/pod
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/pod/{namespace}
GET http://localhost:9090/api/v1/pod/kube-system
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/pod/{namespace}/{pod}
GET http://localhost:9090/api/v1/pod/kube-system/etcd-minikube
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/pod/{namespace}/{pod}/event
GET http://localhost:9090/api/v1/pod/kube-system/etcd-minikube/event
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/pod/{namespace}/{pod}/persistentvolumeclaim
GET http://localhost:9090/api/v1/pod/kube-system/etcd-minikube/event
Accept: application/json
Cache-Control: no-cache

################################################### Test CRUD Node ###################################################
### Test /api/v1/node
GET http://localhost:9090/api/v1/node
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/node/{name}
GET http://localhost:9090/api/v1/node/minikube
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/node/{name}/event
GET http://localhost:9090/api/v1/node/minikube/event
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/node/{name}/pod
GET http://localhost:9090/api/v1/node/minikube/pod?filterBy=name,kube-&sortBy=d,name&itemsPerPage=2&page=1
Accept: application/json
Cache-Control: no-cache

################################################# Test CRUD Namespace ################################################
### Test /api/v1/namespace
POST http://localhost:9090/api/v1/namespace
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "test"
}

### Test /api/v1/namespace
GET http://localhost:9090/api/v1/namespace?filterBy=name,kube-
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/namespace/{name}
GET http://localhost:9090/api/v1/namespace/kube-system
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/namespace/{name}/event
GET http://localhost:9090/api/v1/namespace/kube-system/event
Accept: application/json
Cache-Control: no-cache

################################################# Test CRUD Secret ################################################
### Test /api/v1/secret
GET http://localhost:9090/api/v1/secret?itemsPerPage=2&page=1
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/secret/{namespace}
GET http://localhost:9090/api/v1/secret/default
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/secret/{namespace}/{name}
GET http://localhost:9090/api/v1/secret/default/default-token-n8tj4
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/secret
# .dockercfg format
#{
#    "docker-register-server": {
#          "username":"Your Username",
#          "password":"Your Password",
#          "email":" ",
#          "auth":"base64(Username: password)"
#        }
#}
POST http://localhost:9090/api/v1/secret
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "my-register-server",
  "namespace": "default",
  "data": "base64(.dockercfg)"
}

################################################# Test CRUD ConfigMap ################################################
### Test /api/v1/configmap
GET http://localhost:9090/api/v1/configmap
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/configmap/{namespace}
GET http://localhost:9090/api/v1/configmap/kube-system
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/configmap/{namespace}/{configmap}
GET http://localhost:9090/api/v1/configmap/kube-public/cluster-info
Accept: application/json
Cache-Control: no-cache

############################################# Test CRUD Persistent Volume ############################################
### Test /api/v1/persistentvolume
GET http://localhost:9090/api/v1/persistentvolume
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/persistentvolume/{persistentvolume}
# Note. pv dont have namespace
GET http://localhost:9090/api/v1/persistentvolume/test
Accept: application/json
Cache-Control: no-cache

########################################## Test CRUD Persistent Volume Claim #########################################
### Test /api/v1/persistentvolumeclaim
GET http://localhost:9090/api/v1/persistentvolumeclaim
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/persistentvolumeclaim/{namespace}
GET http://localhost:9090/api/v1/persistentvolumeclaim/default
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/persistentvolumeclaim/{namespace}/{name}
GET http://localhost:9090/api/v1/persistentvolumeclaim/default/test
Accept: application/json
Cache-Control: no-cache

########################################## Test CRUD storageclass #########################################
### Test /api/v1/storageclass
GET http://localhost:9090/api/v1/storageclass
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/storageclass/{storageclass}
GET http://localhost:9090/api/v1/storageclass/test
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/storageclass/{storageclass}/persistentvolume
GET http://localhost:9090/api/v1/storageclass/test/persistentvolume
Accept: application/json
Cache-Control: no-cache

############################################# Test CRUD service ###########################################
### Test /api/v1/service
GET http://localhost:9090/api/v1/service
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/service/{namespace}
GET http://localhost:9090/api/v1/service/default
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/service/{namespace}/{service}

GET http://localhost:9090/api/v1/service/default/kubernetes
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/service/{namespace}/{service}/pod
GET http://localhost:9090/api/v1/service/kube-system/kube-dns/pod
Accept: application/json
Cache-Control: no-cache

############################################# Test logs ###########################################
### Test /log/source/{namespace}/{resourceName}/{resourceType}
GET http://localhost:9090/api/v1/log/source/kube-system/etcd-minikube/pod
Accept: application/json
Cache-Control: no-cache

### Test /log/{namespace}/{pod}
GET http://localhost:9090/api/v1/log/kube-system/etcd-minikube
Accept: application/json
Cache-Control: no-cache

###
GET http://localhost:9090/api/v1/log/kube-system/etcd-minikube?referenceLineNum=1&offsetFrom=0&offsetTo=22&previous=true
Accept: application/json
Cache-Control: no-cache

###
GET http://localhost:9090/api/v1/log/kube-system/etcd-minikube?referenceTimestamp=2018-11-25T10:18:01.16823409Z&referenceLineNum=1&offsetFrom=1&offsetTo=3
Accept: application/json
Cache-Control: no-cache

### Test /log/{namespace}/{pod}/{container}
GET http://localhost:9090/api/v1/log/kube-system/etcd-minikube/etcd
Accept: application/json
Cache-Control: no-cache

### Test /log/file/{namespace}/{pod}/{container}
GET http://localhost:9090/api/v1/log/file/kube-system/etcd-minikube/etcd
Accept: application/json
Cache-Control: no-cache

### Test /log/file/{namespace}/{pod}/{container}
GET http://localhost:9090/api/v1/log/file/kube-system/etcd-minikube/etcd?previous=true
Accept: application/json
Cache-Control: no-cache

############################################# Test rbac ###########################################
### Test /rbac/role
GET http://localhost:9090/api/v1/rbac/role
Accept: application/json
Cache-Control: no-cache

### Test /rbac/rolebinding
GET http://localhost:9090/api/v1/rbac/rolebinding?filterBy=name,weave-net
Accept: application/json
Cache-Control: no-cache

### Test /rbac/status
GET http://localhost:9090/api/v1/rbac/status
Accept: application/json
Cache-Control: no-cache

############################################# Test cluster ###########################################
### Test /rbac/cluster
GET http://localhost:9090/api/v1/cluster
Accept: application/json
Cache-Control: no-cache

############################################# Test replicaset ###########################################
### Test /replicaset
GET http://localhost:9090/api/v1/replicaset
Accept: application/json
Cache-Control: no-cache

### Test /replicaset/{namespace}
GET http://localhost:9090/api/v1/replicaset/kube-system
Accept: application/json
Cache-Control: no-cache

### Test /replicaset/{namespace}/{replicaSet}
GET http://localhost:9090/api/v1/replicaset/kube-system/kube-dns-b4bd9576
Accept: application/json
Cache-Control: no-cache

### Test /replicaset/{namespace}//{replicaSet}/pod
GET http://localhost:9090/api/v1/replicaset/kube-system/kube-dns-b4bd9576/pod
Accept: application/json
Cache-Control: no-cache

### Test /replicaset/{namespace}//{replicaSet}/event
GET http://localhost:9090/api/v1/replicaset/kube-system/kube-dns-b4bd9576/event
Accept: application/json
Cache-Control: no-cache

############################################# Test replication controller ###########################################
### Test /replicationcontroller
GET http://localhost:9090/api/v1/replicationcontroller
Accept: application/json
Cache-Control: no-cache

### Test /replicationcontroller/{namespace}
GET http://localhost:9090/api/v1/replicationcontroller/default
Accept: application/json
Cache-Control: no-cache

### Test /replicationcontroller/{namespace}/{replicationController}
GET http://localhost:9090/api/v1/replicationcontroller/default/test
Accept: application/json
Cache-Control: no-cache

### Test /replicationcontroller/{namespace}/{replicationController}/update/pod
POST http://localhost:9090/api/v1/replicationcontroller/default/test/update/pod
Content-Type: application/json
Cache-Control: no-cache

{
  "replicas": 3
}

### Test /replicationcontroller/{namespace}/{replicationController}/pod
GET http://localhost:9090/api/v1/replicationcontroller/default/test/pod
Content-Type: application/json
Cache-Control: no-cache

### Test /replicationcontroller/{namespace}/{replicationController}/event
GET http://localhost:9090/api/v1/replicationcontroller/default/test/event
Content-Type: application/json
Cache-Control: no-cache

### Test /replicationcontroller/{namespace}/{replicationController}/service
GET http://localhost:9090/api/v1/replicationcontroller/default/test/service
Content-Type: application/json
Cache-Control: no-cache

############################################# Test deployment ###########################################
### Test /deployment
GET http://localhost:9090/api/v1/deployment
Content-Type: application/json
Cache-Control: no-cache

### Test /deployment/{namespace}
GET http://localhost:9090/api/v1/deployment/kube-system
Content-Type: application/json
Cache-Control: no-cache

### Test /deployment/{namespace}/{deployment}
GET http://localhost:9090/api/v1/deployment/kube-system/kube-dns
Content-Type: application/json
Cache-Control: no-cache

### Test /deployment/{namespace}/{deployment}/event
GET http://localhost:9090/api/v1/deployment/kube-system/kube-dns/event
Content-Type: application/json
Cache-Control: no-cache

### Test /deployment/{namespace}/{deployment}
GET http://localhost:9090/api/v1/deployment/kube-system/kube-dns/oldreplicaset
Content-Type: application/json
Cache-Control: no-cache

###