#################################################### Test  AUTH ###################################################
### Test /api/v1/login
POST http://localhost:9090/api/v1/login
Content-Type: application/json
Cache-Control: no-cache

{
  "Token": "test-token"
}

### Test /token/refresh
POST http://localhost:9090/api/v1/token/refresh
Content-Type: application/json
Cache-Control: no-cache

{
  "jweToken": "{\"protected\":\"eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0\",\"aad\":\"eyJleHAiOiIyMDE4LTExLTIxVDIwOjMwOjIwKzA4OjAwIiwiaWF0IjoiMjAxOC0xMS0yMVQyMDoxNToyMCswODowMCJ9\",\"encrypted_key\":\"mjqI30nPCRsbmRg_rMQPxYw5YLRpN-bXePKJzt4Ga0yCPO2Kz3cTSXuwy5cxEdjNQaXbyZ7ztxXgVE83EeUvoN7XG9DLKsFiECH7ZsXTt_Xov2e5XoHXdUWv_pQZRJfWcSyQ2zv5uSA9LbjT2JFNYV9VxOLw6SMocU1YJxu1KwiRteGEQvZ0y9wuCDMY8UkJFrtDBCt0DaTBmLLX1jyT4PBPPbMCnujtPH7E0JNlMjmVCSOEDTQMdrC4jcVescqcGrS-T8YrKejUVRwANKOtOruzIhKYBLDIII2RgiV9redfdPRy847ydOsTHfOQ3J92OyZAYpNrZtGbMGNjsWniUw\",\"iv\":\"omP6G1AXuZ4eOcri\",\"ciphertext\":\"-HfZn6q58cFj2EEizyciOEZvCB2jLED4MvOi3FTBMllseAWt5-QYBDC-lO4\",\"tag\":\"Tg1yDcQ7GTU3sHMa4QDVzA\"}"
}

### Test /login/modes
GET http://localhost:9090/api/v1/login/modes
Accept: application/json
Cache-Control: no-cache

### Test /login/skippable
GET http://localhost:9090/api/v1/login/skippable
Accept: application/json
Cache-Control: no-cache


################################################### Test  csrfToken ################################################
### Test /api/v1/csrftoken/{action}
GET http://localhost:9090/api/v1/csrftoken/get
Content-Type: application/json
Cache-Control: no-cache

################################################### Test CRUD POD ###################################################
### Test /api/v1/pod
GET http://localhost:9090/api/v1/pod
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/pod/{namespace}
GET http://localhost:9090/api/v1/pod/default
Accept: application/json
Cache-Control: no-cache

################################################### Test CRUD Node ###################################################
### Test /api/v1/node
GET http://localhost:9090/api/v1/node
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/node/{name}
GET http://localhost:9090/api/v1/node/minikube
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/node/{name}/event
GET http://localhost:9090/api/v1/node/minikube/event
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/node/{name}/pod
GET http://localhost:9090/api/v1/node/minikube/pod?filterBy=name,kube-&sortBy=d,name&itemsPerPage=2&page=1
Accept: application/json
Cache-Control: no-cache

################################################# Test CRUD Namespace ################################################
### Test /api/v1/namespace
POST http://localhost:9090/api/v1/namespace
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "test"
}

### Test /api/v1/namespace
GET http://localhost:9090/api/v1/namespace?filterBy=name,kube-
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/namespace/{name}
GET http://localhost:9090/api/v1/namespace/kube-system
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/namespace/{name}/event
GET http://localhost:9090/api/v1/namespace/kube-system/event
Accept: application/json
Cache-Control: no-cache

################################################# Test CRUD Secret ################################################
### Test /api/v1/secret
GET http://localhost:9090/api/v1/secret?itemsPerPage=2&page=1
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/secret/{namespace}
GET http://localhost:9090/api/v1/secret/default
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/secret/{namespace}/{name}
GET http://localhost:9090/api/v1/secret/default/default-token-n8tj4
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/secret
# .dockercfg format
#{
#    "docker-register-server": {
#          "username":"Your Username",
#          "password":"Your Password",
#          "email":" ",
#          "auth":"base64(Username: password)"
#        }
#}
POST http://localhost:9090/api/v1/secret
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "my-register-server",
  "namespace": "default",
  "data": "base64(.dockercfg)"
}

################################################# Test CRUD ConfigMap ################################################
### Test /api/v1/configmap
GET http://localhost:9090/api/v1/configmap
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/configmap/{namespace}
GET http://localhost:9090/api/v1/configmap/kube-system
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/configmap/{namespace}/{configmap}
GET http://localhost:9090/api/v1/configmap/kube-public/cluster-info
Accept: application/json
Cache-Control: no-cache

############################################# Test CRUD Persistent Volume ############################################
### Test /api/v1/persistentvolume
GET http://localhost:9090/api/v1/persistentvolume
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/persistentvolume/{persistentvolume}
# Note. pv dont have namespace
GET http://localhost:9090/api/v1/persistentvolume/test
Accept: application/json
Cache-Control: no-cache

########################################## Test CRUD Persistent Volume Claim #########################################
### Test /api/v1/persistentvolumeclaim
GET http://localhost:9090/api/v1/persistentvolumeclaim
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/persistentvolumeclaim/{namespace}
GET http://localhost:9090/api/v1/persistentvolumeclaim/default
Accept: application/json
Cache-Control: no-cache

### Test /api/v1/persistentvolumeclaim/{namespace}/{name}
GET http://localhost:9090/api/v1/persistentvolumeclaim/default/test
Accept: application/json
Cache-Control: no-cache

###
